### ISSUE TITLE
Add a release

### ISSUE THREAD

**Issue by KevinTyrrell** [fouronnes/DingPics#3]
Instead of people cloning the repository, make sure to add a release version, which would correctly download the folder as `DingPics/`, not `DingPics-Master/`.

**Comment by victorpoughon** [comment]
done. but now it downloads as DingPics-0.1. Not sure that's better :/

**Comment by mhco** [comment]
I have added auto-releases using the BigWigs YML file. This will ensure proper releases from hereon out, as well as compatibility with WoWUp and other third-party addon managers.

Go to https://github.com/fouronnes/DingPics/releases/ to see more.
